version: '3.0'

services:
  grafana:
    container_name: 'metrist-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.6}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/metrist-datasource
    extra_hosts:
      - "host.docker.internal:host-gateway"